name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Generate Test Report
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/mochawesome.json
          npx mochawesome-report-generator cypress/reports/mochawesome.json -o cypress/reports/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/videos

      - name: Cache Cypress results
        uses: actions/cache@v3
        with:
          path: cypress/videos
          key: ${{ runner.os }}-cypress-results-${{ github.sha }}
